sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/color/points
    max_range: 1.3
    point_subsample: 2
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 0.2
    filtered_cloud_topic: filtered_cloud
    ns: kinect
